### ISSUE TITLE
Chart not showing

### ISSUE THREAD

**Issue by Amarneh** [stefanwalther/sense-funnel-chart#10]
Dears,

Thank you for the great work.

the extension is working fine on desktop, but on server it's not, I imported it successfully and added dimension and measure, but I can see only the numbers without the chart design.
![untitled](https://cloud.githubusercontent.com/assets/27972005/25353494/759fe3dc-2940-11e7-8215-da9983c646c0.png)

**Comment by stefanwalther** [comment]
Can you please have a look if there are any errors in the browsers console?

**Comment by Amarneh** [comment]
Here you go...
[Errorlog.txt](https://github.com/stefanwalther/sense-funnel-chart/files/991671/Errorlog.txt)
